-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 19:28:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `Nombre_usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deducciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deducciones` (
  `ID_Deducciones` INT NOT NULL AUTO_INCREMENT,
  `Iggs` FLOAT NULL,
  `Bantrab` FLOAT NULL,
  `Isr` FLOAT NULL,
  PRIMARY KEY (`ID_Deducciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comiciones` (
  `ID_Comisiones` INT NOT NULL,
  `Bonificaciones` FLOAT NOT NULL,
  `comicionextra` FLOAT NOT NULL,
  PRIMARY KEY (`ID_Comisiones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Depatamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Depatamentos` (
  `Cod_Departamentos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Departamento` VARCHAR(45) NOT NULL,
  `Depatamentoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Departamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nuevo_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nuevo_Empleado` (
  `DPI_Empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Empleado` VARCHAR(45) NOT NULL,
  `Nit_Empleado` VARCHAR(45) NOT NULL,
  `Direccion_Empleado` VARCHAR(65) NOT NULL,
  `Sueldo_Empleado` FLOAT NOT NULL,
  `Deducciones_ID_Deducciones` INT NOT NULL,
  `comiciones_ID_Comisiones` INT NOT NULL,
  `Depatamentos_Cod_Departamentos` INT NOT NULL,
  PRIMARY KEY (`DPI_Empleado`, `Deducciones_ID_Deducciones`, `comiciones_ID_Comisiones`, `Depatamentos_Cod_Departamentos`),
  INDEX `fk_Nuevo_Empleado_Deducciones_idx` (`Deducciones_ID_Deducciones` ASC) VISIBLE,
  INDEX `fk_Nuevo_Empleado_comiciones1_idx` (`comiciones_ID_Comisiones` ASC) VISIBLE,
  INDEX `fk_Nuevo_Empleado_Depatamentos1_idx` (`Depatamentos_Cod_Departamentos` ASC) VISIBLE,
  CONSTRAINT `fk_Nuevo_Empleado_Deducciones`
    FOREIGN KEY (`Deducciones_ID_Deducciones`)
    REFERENCES `mydb`.`Deducciones` (`ID_Deducciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nuevo_Empleado_comiciones1`
    FOREIGN KEY (`comiciones_ID_Comisiones`)
    REFERENCES `mydb`.`comiciones` (`ID_Comisiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nuevo_Empleado_Depatamentos1`
    FOREIGN KEY (`Depatamentos_Cod_Departamentos`)
    REFERENCES `mydb`.`Depatamentos` (`Cod_Departamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bancos` (
  `ID_Banco` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Banco` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Banco`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
